**1.what is Embeddings??**

-Embeddings are numerical representations of text, images, audio, or any data. For text (usually our focus) an embedding is:

- a vector (a long list of numbers)

- Generated by a model

- Designed so that similar meaning- similar numbers

**2. Why Do we Use Embeddings??**

- because computers don't understand text directly - they understand numbers,

- Embeddings allow systems to:

- Search semantically ('Meaning-based search')

- Build recommendation systems

- Measure similarity between texts

- Cluster docments

- RAF (Retrival-Augmented Generation), including ChatGroq workflows

**3.What is Similarity Score??**

- Once you have embeddding, you measure similarity using a mathematical formula.

- The most common one is:

-Cosine Simlarity:

-it measures the angle between two vectors.

    -1.0 -> identical meaning

    -0.0 -> unrelated

    -1.0 -> Opposite meaning

In [3]:
import sentence_transformers
dir(sentence_transformers)

['CrossEncoder',
 'CrossEncoderModelCardData',
 'CrossEncoderTrainer',
 'CrossEncoderTrainingArguments',
 'DefaultBatchSampler',
 'InputExample',
 'LoggingHandler',
 'MultiDatasetDefaultBatchSampler',
 'ParallelSentencesDataset',
 'SentenceTransformer',
 'SentenceTransformerModelCardData',
 'SentenceTransformerTrainer',
 'SentenceTransformerTrainingArguments',
 'SentencesDataset',
 'SimilarityFunction',
 'SparseEncoder',
 'SparseEncoderModelCardData',
 'SparseEncoderTrainer',
 'SparseEncoderTrainingArguments',
 '__MODEL_HUB_ORGANIZATION__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 'annotations',
 'backend',
 'cross_encoder',
 'data_collator',
 'datasets',
 'evaluation',
 'export_dynamic_quantized_onnx_model',
 'export_optimized_onnx_model',
 'export_static_quantized_openvino_model',
 'fit_mixin',
 'importlib',
 'losses',
 'mine_hard_negatives',
 'model_card',
 'model_card_

In [4]:
from sentence_transformers import SentenceTransformer
import numpy as np

In [14]:
import warnings
warnings.filterwarnings('ignore')

In [17]:
model=SentenceTransformer('all-MiniLm-L6-v2')

In [18]:
model

SentenceTransformer(
  (0): Transformer({'max_seq_length': 256, 'do_lower_case': False, 'architecture': 'BertModel'})
  (1): Pooling({'word_embedding_dimension': 384, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
  (2): Normalize()
)

In [15]:
sentences=[
    "I like apples.",
    "I enjoy eating apples.",
    "I drive a motorcycle"
]

In [19]:
embedding=model.encode(sentences)

In [20]:
embedding

array([[-0.00795676,  0.00439062,  0.0020251 , ...,  0.05261282,
         0.09204271,  0.01492961],
       [ 0.04228432, -0.02286877,  0.0109918 , ...,  0.04014785,
         0.01113552, -0.02590695],
       [ 0.00867908,  0.02741997,  0.01690438, ...,  0.0561426 ,
        -0.00878816, -0.12268245]], dtype=float32)

In [21]:
len(embedding)

3

In [22]:
embedding[0]

array([-7.95676280e-03,  4.39061550e-03,  2.02510459e-03,  4.47826199e-02,
       -4.11381051e-02, -1.17856506e-02,  9.93527845e-02, -1.49924727e-02,
        3.28452215e-02,  2.80842669e-02,  3.82004790e-02, -3.95743288e-02,
        3.20650041e-02, -1.52864400e-02,  3.38638201e-02,  7.11707631e-03,
        6.39917776e-02, -4.05895114e-02, -4.73221652e-02, -1.12335933e-02,
       -7.96146691e-02,  7.19404817e-02,  5.19621670e-02, -1.93749741e-02,
        9.35395772e-04,  4.32007797e-02,  1.97203793e-02, -3.00485454e-02,
       -8.23600739e-02, -3.70824076e-02, -5.02395444e-02,  1.10583305e-02,
        2.05313098e-02,  1.45488074e-02, -3.76089327e-02,  1.48733212e-02,
        1.00732192e-01, -3.48993875e-02, -2.48852391e-02, -1.85873173e-02,
        1.62230153e-03,  5.87750934e-02,  5.86785227e-02,  5.20197749e-02,
       -5.73278181e-02, -1.06776189e-02,  3.00519783e-02, -4.60932590e-02,
        9.38397869e-02,  5.82442619e-02,  6.42052218e-02, -9.02735977e-04,
       -4.48685884e-02, -

In [23]:
len(embedding[0])   #i like apple information avabul here

384

In [28]:
v1=embedding[0].reshape(-1,1) # i like apples
v2=embedding[1].reshape(-1,1) # i enjoy eat apple
v3=embedding[2].reshape(-1,1)# i drive a motorecycle

In [29]:
from sklearn.metrics.pairwise import cosine_similarity

In [30]:
cosine_similarity(v1,v2)

array([[-1.,  1., -1., ..., -1., -1.,  1.],
       [ 1., -1.,  1., ...,  1.,  1., -1.],
       [ 1., -1.,  1., ...,  1.,  1., -1.],
       ...,
       [ 1., -1.,  1., ...,  1.,  1., -1.],
       [ 1., -1.,  1., ...,  1.,  1., -1.],
       [ 1., -1.,  1., ...,  1.,  1., -1.]], dtype=float32)

In [32]:
def cosine_sim(a,b):
    return np.dot(a,b)/(np.linalg.norm(a) * np.linalg.norm(b))

In [33]:
v1=embedding[0]
v2=embedding[1]
cosine_sim(v1,v2)

np.float32(0.837434)

In [34]:
v1=embedding[0]
v3=embedding[2]
cosine_sim(v1,v3)

np.float32(0.20200358)

In [38]:
nr=np.dot(v1,v2)
norm_v1=np.linalg.norm(v1)
norm_v2=np.linalg.norm(v2)
dr=norm_v1*norm_v2
cosine_sim(v1,v2),nr/dr

(np.float32(0.837434), np.float32(0.837434))

In [40]:
nr=np.dot(v1,v3)
norm_v1=np.linalg.norm(v1)
norm_v2=np.linalg.norm(v3)
dr=norm_v1*norm_v2
cosine_sim(v1,v2),nr/dr

(np.float32(0.837434), np.float32(0.20200358))